### ISSUE TITLE
Abgeschnittener Text

### ISSUE THREAD

**Issue by heumann-a** [ratisbona-coding/website#8]
## Steps to Reproduce the Problem

1. Aktiviere die Developer ansicht 
2. Schalte in Mobile Devices um
3. Wähle iPad Air und drehe in Querformat

![image](https://user-images.githubusercontent.com/42214189/203347003-da758753-cb11-4281-8b54-6e2650bdeb56.png)

Verursacht durch eine Höhen-Begrenzung in Zeile https://github.com/ratisbona-coding/website-new/blob/68a975459469fb463356f35cf8303d0e2a21ebfe/src/routes/landing/Projekte.svelte#L55

`<div class="mb-40 box-border h-32">`

**Comment by Schkai** [comment]
Fixed in https://github.com/ratisbona-coding/website/pull/11
